### ISSUE TITLE
Glossary's "related page" not working

### ISSUE THREAD

**Issue by flavioazevedo** [forrtproject/forrtproject.github.io#96] opened 2024-04-09 11:59 UTC
The entries of the Glossary have a "Related Terms" that connects other similar terms so that folks can hop from one entry to another via internal hyperlinks. Now, unfortunately, it only has the code and not the hyperlinks: 

See example here: 
https://forrt.org/glossary/analytic-flexibility/
![image](https://github.com/forrtproject/forrtproject.github.io/assets/18330492/5d63f072-6f17-4be4-807d-6dd0ed1d5e4c)

which reads: "<a href=/glossary/garden-of-forking-paths/>Garden of forking paths</a>, <a href=/glossary/multiverse-analysis/>Multiverse analysis</a>, <a href=/glossary/researcher-degrees-of-freedom/>Researcher degrees of freedom</a>"

**Comment by richarddushime** [comment] 2024-04-15 06:50
I tried to reproduce the error  but on localhost, All is working  well 
Not sure what could be the cause.

**Comment by SamGuay** [comment] 2024-04-17 00:10
Closing since #97 was merged. Reopen if problem persists.

**Closed by SamGuay** 2024-04-17 00:10 UTC
